load("//bazel:build_system.bzl", "zoo_cc_module")

package(default_visibility = ["//visibility:public"])

zoo_cc_module(
    name = "zoo.reptiles.snake",
    src = "snake.ixx",
    impl_srcs = [
        "snake.cc",
    ],
)
