load("//bazel:build_system.bzl", "zoo_cc_module")

package(default_visibility = ["//visibility:public"])

zoo_cc_module(
    name = "zoo.mammals.tiger",
    src = "tiger.ixx",
    impl_srcs = [
        "tiger.cc",
    ],
)
